### PR TITLE
Add failing test demonstrating issue with setting proxy servers

### PR DESCRIPTION
**Pull request by flux-ricky**
**Requirements**

- [ ] I have added test coverage for new or changed functionality
- [ ] I have followed the repository's [pull request submission guidelines](../blob/master/CONTRIBUTING.md#submitting-pull-requests)
- [ ] I have validated my changes against all supported platform versions

**Related issues**

Provide links to any issues in this repository or elsewhere relating to this pull request.

**Describe the solution you've provided**

Provide a clear and concise description of what you expect to happen.

**Describe alternatives you've considered**

Provide a clear and concise description of any alternative solutions or features you've considered.

**Additional context**

Add any other context about the pull request here.

### CODE REVIEW

**Comment by eli-darkly** [comment]
Did you intend to open this PR yet? You haven't filled out any of the information we ask for in the description form, and there's no open issue related to this.

**Comment by flux-ricky** [comment]
Updating the code to set the proxy settings breaks the test suite in an odd way. Something is up with the stub http and proxy servers and how they accept and respond to requests.

**Comment by flux-ricky** [comment]
@eli-darkly sorry, I did not. I did this quickly and was intending the PR to made into my fork! Sorry, I have only now seen my mistake. I pushed this up so that a colleague to link to it when contacting LD support. I will close this now as all I intended for it was to on a remote to be linked to.

**Comment by flux-ricky** [comment]
And for clarification this is not something I am continuing to work on personally at this time. Sorry for the disruption.

**Pull request closed without merging**
